### PR TITLE
Falcon added more power to the engines

### PR DESCRIPTION
**Pull request by IAHM-COL**
And now the beech seem to have enough power to lift

### CODE REVIEW

**Comment by IAHM-COL** [comment]
@helijah 

Dear Emmanuel

Falcon has tweeked a little the engine power of the Beechcraft C18S
Maybe you may want to take a look at his proposal changes and decide if these can be merged into the mainstream

best,
@IAHM-COL

**Comment by helijah** [comment]
I'm sorry, but the engines are advertised 450 hp maximum. Put 650 hp is a total heresy and not complete sense.

http://en.wikipedia.org/wiki/Pratt_%26_Whitney_R-985_Wasp_Junior
http://en.wikipedia.org/wiki/Beechcraft_Model_18

There are one versions to 600 hp, but it's not the engines that were on the C18s..

Regards Emmanuel

**Comment by IAHM-COL** [comment]
@helijah 
Thanks Emmanuel. Nothing to be sorry about ;)
I am closing this case then
Best
IH-COL

**Comment by JWocky** [comment]
Falcon asked me a while ago to make that change for his PRIVATE and exclusively JUST FOR FUN USE, this was never intended to go public! Sorry for the inconvenience I caused, Emanuel!

**Comment by helijah** [comment]
lol. For personal and private use, it is obvious that he can do what he want :) Even add reactors if he wants lol

**Comment by JWocky** [comment]
True, but I really would like to see him doing that to a plane, It would improve his skills.

**Comment by IAHM-COL** [comment]
I agree :d  
It would be great to help falcon become a proficient plane tinkerer. Even if it takes to make some unrealistic first attempts

**Pull request closed without merging**
